In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

2024-02-12 22:34:40.096854: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-12 22:34:40.097073: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-12 22:34:40.113292: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-12 22:34:40.179140: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-12 22:34:41.554018: W tensorflow/compiler/tf2

In [2]:
import tensorflow as tf

In [3]:
tf.config.list_physical_devices()

2024-02-12 22:34:43.385808: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-02-12 22:34:43.491791: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-02-12 22:34:43.491866: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
reviews = ['nice food',
           'amazing restaurant',
           'too good',
           'just loved it!',
           'will go again',
           'horrible food',
           'never go there',
           'poor service',
           'poor quality',
           'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [5]:
one_hot("amazing restaurant", 50)

[4, 9]

In [6]:
vocab_size = 50
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[28, 47], [4, 9], [24, 7], [5, 48, 14], [25, 29, 32], [1, 47], [31, 29, 18], [24, 27], [24, 33], [49, 2]]


In [7]:
encoded_reviews

[[28, 47],
 [4, 9],
 [24, 7],
 [5, 48, 14],
 [25, 29, 32],
 [1, 47],
 [31, 29, 18],
 [24, 27],
 [24, 33],
 [49, 2]]

In [8]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[28, 47,  0],
       [ 4,  9,  0],
       [24,  7,  0],
       [ 5, 48, 14],
       [25, 29, 32],
       [ 1, 47,  0],
       [31, 29, 18],
       [24, 27,  0],
       [24, 33,  0],
       [49,  2,  0]], dtype=int32)

In [9]:
embedded_vector_size = 5
model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))


2024-02-12 22:34:43.662587: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-02-12 22:34:43.662735: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-02-12 22:34:43.662789: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-02-12 22:34:44.186542: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-02-12 22:34:44.186720: I external/local_xla/xla/stream_executor

In [10]:
x = padded_reviews
y = sentiment

In [11]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              250       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 266 (1.04 KB)
Trainable params: 266 (1.04 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.fit(x, y, epochs=50, verbose=0)

2024-02-12 22:34:46.520092: I external/local_xla/xla/service/service.cc:168] XLA service 0x7fde3033ea90 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-02-12 22:34:46.520173: I external/local_xla/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce GTX 1650 Ti, Compute Capability 7.5
2024-02-12 22:34:46.535229: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-02-12 22:34:46.576634: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:454] Loaded cuDNN version 8904
I0000 00:00:1707757486.732174    2135 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


In [13]:
loss, accuracy = model.evaluate(x, y)

1/1 [==============================] - 0s 179ms/step - loss: 0.6200 - accuracy: 0.9000


In [14]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

50

In [15]:
weights[28]

array([ 0.07261591,  0.05772696, -0.07496065,  0.03076631, -0.07026308],
      dtype=float32)

In [16]:
weights[4]

array([ 0.01285178,  0.0642539 , -0.05531663,  0.00388419, -0.01652565],
      dtype=float32)